server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://user-service-service.default.svc.cluster.local:80
              predicates:
                - Path=/user/**
            - id: report-service
              uri: http://report-service-service.default.svc.cluster.local:80
              predicates:
                - Path=/report/**
            - id: edu-service
              uri: http://edu-service-service.default.svc.cluster.local:80
              predicates:
                - Path=/edu/**
            - id: recommend-service
              uri: http://recommend-service-service.default.svc.cluster.local:80
              predicates:
                - Path=/recommend/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 3600000 # 엑세스 토큰 만료 시간
  refresh-token-validity: 120960000 # 리프레시 토큰 만료 시간