server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - PreserveHostHeader
          routes:
            - id: user-service
              uri: http://user-service-service.default.svc.cluster.local:80
              predicates:
                - Path=/user/**
              filters:
                - RemoveRequestHeader=Cookie
            - id: report-service
              uri: http://report-service-service.default.svc.cluster.local:80
              predicates:
                - Path=/report/**
              filters:
                - RemoveRequestHeader=Cookie
            - id: edu-service
              uri: http://edu-service-service.default.svc.cluster.local:80
              predicates:
                - Path=/edu/**
              filters:
                - RemoveRequestHeader=Cookie
            - id: recommend-service
              uri: http://recommend-service-service.default.svc.cluster.local:80
              predicates:
                - Path=/recommend/**
              filters:
                - RemoveRequestHeader=Cookie

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 180000  # 3분(3 * 60 * 1000)
  refresh-token-validity: 120960000 # 리프레시 토큰 만료 시간